package com.gunshippenguin.openflood.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class settings extends SVGRenderer {

    public settings(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(64.0f);
        mHeight = dip2px(64.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 20.0f;
        final float scaleY = h / 20.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(15.95f, 10.78f);
        mPath.rCubicTo(0.03f, -0.25f, 0.05f, -0.51f, 0.05f, -0.78f);
        mPath.rCubicTo(0.0f, -0.2699995f, -0.02f, -0.53f, -0.06f, -0.78f);
        mPath.rLineTo(1.69f, -1.32f);
        mPath.rCubicTo(0.15f, -0.12f, 0.19f, -0.34f, 0.1f, -0.51f);
        mPath.rLineTo(-1.6f, -2.77f);
        mPath.rCubicTo(-0.1f, -0.18f, -0.31f, -0.24f, -0.49f, -0.18f);
        mPath.rLineTo(-1.99f, 0.8f);
        mPath.rCubicTo(-0.42f, -0.32f, -0.86f, -0.58f, -1.35f, -0.78f);
        mPath.lineTo(12.0f, 2.34f);
        mPath.rCubicTo(-0.03f, -0.2f, -0.2f, -0.34f, -0.4f, -0.34f);
        mPath.lineTo(8.4f, 1.9999999f);
        mPath.rCubicTo(-0.2f, 0.0f, -0.36f, 0.14f, -0.39f, 0.34f);
        mPath.rLineTo(-0.3f, 2.12f);
        mPath.rCubicTo(-0.49f, 0.2f, -0.94f, 0.47f, -1.35f, 0.78f);
        mPath.rLineTo(-1.99f, -0.8f);
        mPath.rCubicTo(-0.18f, -0.07f, -0.39f, 0.0f, -0.49f, 0.18f);
        mPath.rLineTo(-1.6f, 2.77f);
        mPath.rCubicTo(-0.1f, 0.18f, -0.06f, 0.39f, 0.1f, 0.51f);
        mPath.rLineTo(1.69f, 1.32f);
        mPath.rCubicTo(-0.04f, 0.25f, -0.07f, 0.52f, -0.07f, 0.78f);
        mPath.rCubicTo(0.0f, 0.25999928f, 0.02f, 0.53f, 0.06f, 0.78f);
        mPath.lineTo(2.37f, 12.1f);
        mPath.rCubicTo(-0.15f, 0.12f, -0.19f, 0.34f, -0.1f, 0.51f);
        mPath.rLineTo(1.6f, 2.77f);
        mPath.rCubicTo(0.1f, 0.18f, 0.31f, 0.24f, 0.49f, 0.18f);
        mPath.rLineTo(1.99f, -0.8f);
        mPath.rCubicTo(0.42f, 0.32f, 0.86f, 0.58f, 1.35f, 0.78f);
        mPath.rLineTo(0.3f, 2.12f);
        mPath.rCubicTo(0.04f, 0.2f, 0.2f, 0.34f, 0.4f, 0.34f);
        mPath.rLineTo(3.2f, 0f);
        mPath.rCubicTo(0.2f, 0.0f, 0.37f, -0.14f, 0.39f, -0.34f);
        mPath.rLineTo(0.3f, -2.12f);
        mPath.rCubicTo(0.49f, -0.2f, 0.94f, -0.47f, 1.35f, -0.78f);
        mPath.rLineTo(1.99f, 0.8f);
        mPath.rCubicTo(0.18f, 0.07f, 0.39f, 0.0f, 0.49f, -0.18f);
        mPath.rLineTo(1.6f, -2.77f);
        mPath.rCubicTo(0.1f, -0.18f, 0.06f, -0.39f, -0.1f, -0.51f);
        mPath.rLineTo(-1.67f, -1.32f);
        mPath.close();
        mPath.moveTo(15.95f, 10.78f);
        mPath.moveTo(10.0f, 13.0f);
        mPath.rCubicTo(-1.65f, 0.0f, -3.0f, -1.35f, -3.0f, -3.0f);
        mPath.rCubicTo(0.0f, -1.6499996f, 1.35f, -3.0f, 3.0f, -3.0f);
        mPath.rCubicTo(1.6499996f, 0.0f, 3.0f, 1.35f, 3.0f, 3.0f);
        mPath.rCubicTo(0.0f, 1.6499996f, -1.35f, 3.0f, -3.0f, 3.0f);
        mPath.close();
        mPath.moveTo(10.0f, 13.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}